### ISSUE TITLE
As a Doc Maintainer I would like to comment specs

### ISSUE THREAD

**Issue by mere-teresa** [ezsystems/specs#20]
To be aware of the coming features, I would like to be able to ask questions and put comment on specifications before they become final, to be sure, I understand the topics and the impacts on the product (and therefore on my Precious Documentation :gem: ).

Do you think we can use the Pull Request system to achieve that ?

It's linked to the #1 issue, I think.

**Comment by DavidLiedle** [comment]
@mere-teresa This is a challenge, for sure. Yes, I think using Pull Requests will be the easiest way to discuss. There are also issues like this one, in case there are questions/comments outside of a pull request. One more place discussions can happen is on a single commit. Unfortunately, there's not really a way to just go to a file and add a note, but if you link to the file from an issue like this one (or a comment on a PR or a commit), it should stay pretty easy to follow. This is still something to figure out together, for the best way to keep discussions organized. In general, requirements and specs should appear in a PR as a result of an issue calling for the work to be performed, so there should always be a place to comment on anything coming in. (That won't always be the case, if somebody just proposes something unrelated to an open issue.)

**Comment by andrerom** [comment]
Best way to allow discussion is to always use PR's, essentially that could be long running feature branchs with corresponding PR open against master.

Meaning what is in master is accepted, and what is in list of PR's is WIP features _(using labels or project board to show which stage spec is in)_.

**Comment by DavidLiedle** [comment]
Resolved: use PRs, discuss there. Closing this thread and repo; conversations may continue at the new repo here: https://github.com/ezsystems/requirements/
